In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets
titanic_data=pd.read_csv('0000000000002429_training_titanic_x_y_train.csv')
#print(titanic_data)
def f(str):
    if str=="S":
        return 0
    elif str=='c':
        return 1
    else:
        return 2

def fu(s):
    if s<=16:
        return 0
    elif s>16 and s<=32:
        return 1
    elif s>32 and s<=48:
        return 2
    elif s>48 and s<=64:
        return 3
    else:
        return 4
        
def fus(s):
    if 'Master' in s:
        return 0
    elif 'Miss' in s:
        return 1
    elif 'Mr' in s:
        return 2
    elif 'Mrs' in s:
        return 3
    elif 'Royalty' in s:
        return 4
    else:
        return 5

x_train=titanic_data.copy()

x_train['class']=x_train.Name.apply(fus)
x_train.drop('Name',inplace=True,axis=1)
x_train['Sex']=x_train['Sex'].map({'female':1,'male':0}).astype(int)
x_train.drop('Ticket',inplace=True,axis=1)
x_train.drop('Cabin',inplace=True,axis=1)
x_train.drop('Fare',inplace=True,axis=1)
x_train['family']=x_train['SibSp']+x_train['Parch']+1
del x_train['SibSp']
del x_train['Parch']
x_train['Embarke']=x_train.Embarked.apply(f)
x_train.drop('Embarked',inplace=True,axis=1)

x_train.drop('Survived',inplace=True,axis=1)
x_train.Age.fillna(x_train.Age.mean(),inplace=True)
x_train['new_age']=x_train.Age.apply(fu)
del x_train['Age']
xtrain=x_train

ytrain=titanic_data.Survived
print(xtrain)


arg=DecisionTreeClassifier()
arg.fit(xtrain,ytrain)
x_test=pd.read_csv('0000000000002429_test_titanic_x_test.csv')

x_test['class']=x_test.Name.apply(fus)
x_test.drop('Name',inplace=True,axis=1)
x_test['Sex']=x_test['Sex'].map({'female':1,'male':0}).astype(int)
x_test.drop('Ticket',inplace=True,axis=1)
x_test.drop('Cabin',inplace=True,axis=1)

x_test.drop('Fare',inplace=True,axis=1)
x_test['family']=x_test['SibSp']+x_test['Parch']+1
del x_test['SibSp']
del x_test['Parch']
x_test['Embarke']=x_test.Embarked.apply(f)
x_test.drop('Embarked',inplace=True,axis=1)

x_test.Age.fillna(x_test.Age.mean(),inplace=True)
x_test['new_age']=x_test.Age.apply(fu)
del x_test['Age']
print(x_test)
pred=arg.predict(x_test)

np.savetxt('titanic4.csv',pred,delimiter=',')

     Pclass  Sex  class  family  Embarke  new_age
0         2    1      2       2        0        1
1         3    0      2       1        0        1
2         2    0      2       1        0        2
3         3    1      2       5        0        1
4         3    0      2       1        0        1
..      ...  ...    ...     ...      ...      ...
663       2    1      1       1        0        1
664       3    0      2       1        2        1
665       3    0      2       1        0        1
666       3    1      1       1        0        1
667       3    1      1       2        2        1

[668 rows x 6 columns]
     Pclass  Sex  class  family  Embarke  new_age
0         2    0      0       3        0        0
1         1    1      5       1        0        3
2         3    0      2       1        2        1
3         2    1      2       4        0        1
4         1    0      2       1        0        2
..      ...  ...    ...     ...      ...      ...
218       3    0      2       2        0        1
219       1    0      5       1        0        2
220       1    1      2       2        2        1
221       3    0      2       1        0        2
222       2    0      2       3        0        2

[223 rows x 6 columns]